#设置环境配置
spring:
  profiles:
    active: dev
#设置spring-boot 编码格式
  banner:
    charset: utf-8
  messages:
    encoding: UTF-8
  application:
    name: propertySystem
server:
  tomcat:
    uri-encoding: utf-8
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
